# Generated by Django 6.0.1 on 2026-02-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_tag_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
